### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by geneticsmcgill** [qlu-lab/TITANS#1] opened 2019-11-14 23:06 UTC
Hi there, 

I'm getting a weird issue below (which I'm assuming is about my FAM file. However, my fam file is in standard plink forward (attached below). Do you understand what may be happening? Thanks so much.

Error in fam.par[, 1] : incorrect number of dimensions
Calls: colsplit -> str_split_fixed -> str_split -> stri_split_regex
Execution halted

Fam file example:
FAM0300 RJ0273 RJ0267 RJ0266 1 2
FAM0300 RJ0266 0 0 2 2
FAM0300 RJ0267 0 0 1 1
FAM0312 RJ0562 RJ0534 RJ0279 1 2
FAM0312 RJ0279 0 0 2 1
FAM0312 RJ0534 0 0 1 2

**Comment by KunlingHuang** [comment] 2019-11-15 08:15
Hi, thanks for reaching out. Is there any families with only one parent in your data (either fam or vcf file)? I assume the inputs are trios (two non-diseased parents and a diseased offspring), including families with only one parent will cause this error. 

Also, I noticed that there are diseased parents in your data. TITANS is designed for detecting transmission disequilibrium between proband and pseudosiblings. Pseudosiblings are supposed to be generated from non-diseased parents otherwise the analysis will be biased. As a result, trios with two non-diseased parents and a diseased offspring will be suitable for TITANS.

Let me know if you have any questions!

**Comment by geneticsmcgill** [comment] 2019-11-15 18:00
Hi there. Thanks so much for the prompt response!

My data consists of full trios. Not sure what else may be causing it. Does the fam file have to be delimited by a something specific?

 I didn’t know about the affection status, so I’ll remove those trios. What would you say is the appropriate number of trios for sufficient power?

Cheers,
Cal

On Nov 15, 2019, at 3:15 AM, Kunling Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, thanks for reaching out. Is there any families with only one parent in your data? I assume the inputs are trios (two non-diseased parents and a diseased offspring), including families with only one parent will cause this error.

Also, I noticed that there are diseased parents in your data. TITANS is designed for detecting transmission disequilibrium between proband and pseudosiblings. Pseudosiblings are supposed to be generated from non-diseased parents otherwise the analysis will be biased. As a result, trios with two non-diseased parents and a diseased offspring will be suitable for TITANS.

Let me know if you have any questions!

**Comment by geneticsmcgill** [comment] 2019-11-15 18:02
Hi there. Thanks so much for the prompt response!

My data consists of full trios. Not sure what else may be causing it. Does the fam file have to be delimited by a something specific? I've tried both space and tab. 

 I didn’t know about the affection status, so I’ll remove those trios. What would you say is the appropriate number of trios for sufficient power?

**Comment by KunlingHuang** [comment] 2019-11-15 18:36
Hi, I use tab as delimiter for fam file. Did you go through the tutorial? Did it run successfully? This issue looks like fam.par is not a data.frame and this will be caused by families in the data with only 1 parent present in the family. Would you mind describing your data?

For the power issue, power depends on the disease mechanism and it is lower than GWAS with similar scale of samples. For example, using 7805 autism trios (31220 probands and pseudosiblings) identified 2 associations having p-value about 5e-8.

**Comment by geneticsmcgill** [comment] 2019-11-15 21:05
I've tested the tutorial and it worked well. I even tested the tutorial on my vcf and fam and it worked but had NA for p-value. 

My data consists of several hundred complete trios (both parents + proband). Any families that are incomplete were removed prior. I could send you my fam file if that would help.

**Comment by KunlingHuang** [comment] 2019-11-15 21:12
Sounds good, can I also have the IDs in the vcf file? If you include half-parent it will also cause error. I wanted to check if that's the case.

I am not sure what do you mean by "testing the tutorial on your vcf and fam", the gene expression imputation model is fake (this gene has eQTLs rs1 to rs10 on chromosome 1), if you use this fake gene expression imputation model no SNP will be included in the model and that's why you got NA.

**Comment by geneticsmcgill** [comment] 2019-11-15 21:21
Thank you so much. I’ve attached the file below. The header as well.



On Nov 15, 2019, at 4:12 PM, Kunling Huang <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds good, can I also have the IDs in the vcf file? If you include half-parent it will also cause error. I wanted to check if that's the case.

I am not sure what do you mean by "testing the tutorial on your vcf and fam", the gene expression imputation model is fake (this gene has eQTLs rs1 to rs10 on chromosome 1), if you use this fake gene expression imputation model no SNP will be included in the model and that's why you got NA.

**Comment by KunlingHuang** [comment] 2019-11-15 21:28
Hi, I didn't see any attachments, maybe send them to khuang82@wisc.edu?

**Closed as completed** 2019-11-25 17:41 UTC
